site_name: RSS101
repo_url: https://github.com/Colin-XKL/rss101
repo_name: Colin-XKL/rss101
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate 
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

  
nav:
  - Home: 'index.md'
  - "起步": "introduction/introduction.md"
  - "发现订阅源": 
    - "如何寻找订阅源": "find-feed/find-feed.md"
    - "订阅源合集与推荐": "find-feed/recommend.md"
  - "阅读RSS": 
    - "RSS阅读器概述": "read-feed/read-feed.md"
    - "网页端的 RSS 阅读器": "read-feed/reader-for-web.md"
    - "Mac 上的 RSS 阅读器": "read-feed/reader-for-mac.md"
    - "iOS 上的 RSS 阅读器": "read-feed/reader-for-ios.md"
    - "Win 上的 RSS 阅读器": "read-feed/reader-for-win.md"
    - "Android 上的 RSS 阅读器": "read-feed/reader-for-android.md"
    - "Linux 上的 RSS 阅读器": "read-feed/reader-for-linux.md"
  - RSSMan: 
    - "概述": "deploy/deploy.md"
    - "RSSMAN 介绍": "deploy/rssman.md"
    - "完整流程": "deploy/rssman-full-guide.md"
  - "DIY 订阅源": 
    - "概述": "make-feed/make-feed.md"
    - "Huginn": "make-feed/huginn.md"
  - "进阶":
    - "概述": "advance/advance.md"
  - About: 'about/about.md'